services:
  - type: web
    name: digital-dudes-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        value: DigitalDudes2026SecretKey
      - key: JWT_EXPIRE
        value: 7d
      - key: MONGODB_URI
        value: mongodb+srv://digitaldudes18_db_user:4jeyXrAXrqXTMizs@cluster0.zgql3hs.mongodb.net/digital-dudes?retryWrites=true&w=majority&appName=Cluster0
      - key: FRONTEND_URL
        value: http://localhost:5173
